# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdb3392db73be039424f95357af863d6bfae7b9999117a2073d9e0c10acd8f70db92a392878b7a70a56e95453729e4c8338614d88731f7a3745aec735983f3e6

test:
  secret_key_base: a1283f1afa236123d4000d039905e51c7e1808b2acfbd4d4350bbc47b7622e4cd9d91cfd8a18207d51a12f182a3a177ad62042075e8dfe7c72eb4c30b8dc63ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
